package com.example.shape.Util.Send;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://Gmcc.SiniOA.Com/")
public interface ServiceSoap {

	/**
	 * 
	 * @param dcmr
	 * @return returns test.DCMResponse
	 */
	@WebMethod(operationName = "ClientForDCM", action = "http://Gmcc.SiniOA.Com/ClientForDCM")
	@WebResult(name = "ClientForDCMResult", targetNamespace = "http://Gmcc.SiniOA.Com/")
	@RequestWrapper(localName = "ClientForDCM", targetNamespace = "http://Gmcc.SiniOA.Com/", className = "test.ClientForDCM")
	@ResponseWrapper(localName = "ClientForDCMResponse", targetNamespace = "http://Gmcc.SiniOA.Com/", className = "test.ClientForDCMResponse")
	public DCMResponse clientForDCM(
            @WebParam(name = "DCMR", targetNamespace = "http://Gmcc.SiniOA.Com/") DCMRequest dcmr);

}
